[package]
name = "mayastor-macros"
version = "0.1.0"
authors = ["Tiago Castro <tiagolobocastro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
proc-macro = true